// posts requests

GET http://localhost:3000/posts

GET http://localhost:3000/post?sender=673b12b31d4adf85ab35c840

Get http://localhost:3000/post/674340937f923c00ebeaebfe

PUT http://localhost:3000/post/674340937f923c00ebeaebfe
Content-Type: application/json
{
  "content": "Test change post"
}

POST http://localhost:3000/post 
Content-Type: application/json
{
    "message": "Test",
    "sender": "rest test"
}

// comments requests
POST http://localhost:3000/comment/
Content-Type: application/json
{
  "message": "Test comment",
  "sender": "nastia",
  "postId": "674340937f923c00ebeaebfe"
}

GET http://localhost:3000/comment

GET http://localhost:3000/comment/674352d71414f65180ff25e0

DELETE http://localhost:3000/comment/674359beee72b211cc05785e

PUT http://localhost:3000/comment/674359beee72b211cc05785e
Content-Type: application/json
{
    "message": "Test",
    "postId": "67434f56f3b4d522b88ff718",
    "sender": "TestUser"
}